/**
 * Curated catalog of molecules to fetch from PubChem.
 *
 * Generated by the build-molecule-catalog workflow: each CID was resolved and
 * verified against PubChem (name -> CID -> formula). To add more molecules, find
 * the compound on pubchem.ncbi.nlm.nih.gov, copy its CID, add a line here, and
 * re-run `npm run data:build`.
 */
export const CATALOG = [
  // --- Gases & diatomics (17) ---
  { cid: 222,        category: "gases",                   }, // Ammonia
  { cid: 280,        category: "gases",                   }, // Carbon Dioxide
  { cid: 281,        category: "gases",                   }, // Carbon Monoxide
  { cid: 297,        category: "gases",                   }, // Methane
  { cid: 313,        category: "gases",                   }, // Hydrochloric Acid
  { cid: 402,        category: "gases",                   }, // Hydrogen Sulfide
  { cid: 783,        category: "gases",                   }, // Hydrogen
  { cid: 947,        category: "gases",                   }, // Nitrogen
  { cid: 948,        category: "gases",                   }, // Nitrous Oxide
  { cid: 977,        category: "gases",                   }, // Oxygen
  { cid: 1119,       category: "gases",                   }, // Sulfur Dioxide
  { cid: 6325,       category: "gases",                   }, // Ethylene
  { cid: 24524,      category: "gases",                   }, // Fluorine
  { cid: 24526,      category: "gases",                   }, // Chlorine
  { cid: 24823,      category: "gases",                   }, // Ozone
  { cid: 145068,     category: "gases",                   }, // Nitric Oxide
  { cid: 3032552,    category: "gases",                   }, // Nitrogen Dioxide

  // --- Inorganic acids & bases (15) ---
  { cid: 176,        category: "acids-bases",             }, // Acetic Acid
  { cid: 260,        category: "acids-bases",             }, // Hydrogen Bromide
  { cid: 767,        category: "acids-bases",             }, // Carbonic Acid
  { cid: 944,        category: "acids-bases",             }, // Nitric Acid
  { cid: 1004,       category: "acids-bases",             }, // Phosphoric Acid
  { cid: 1118,       category: "acids-bases",             }, // Sulfuric Acid
  { cid: 7628,       category: "acids-bases",             }, // Boric Acid
  { cid: 14797,      category: "acids-bases",             }, // Potassium Hydroxide
  { cid: 14798,      category: "acids-bases",             }, // Sodium Hydroxide
  { cid: 14917,      category: "acids-bases",             }, // Hydrofluoric Acid
  { cid: 14923,      category: "acids-bases",             }, // Ammonium Hydroxide
  { cid: 24247,      category: "acids-bases",             }, // Perchloric Acid
  { cid: 73981,      category: "acids-bases",             }, // Magnesium Hydroxide
  { cid: 516892,     category: "acids-bases",             }, // Sodium Bicarbonate
  { cid: 6093208,    category: "acids-bases",             }, // Calcium Hydroxide

  // --- Water, oxides & inorganic salts (9) ---
  { cid: 784,        category: "inorganic-misc",          }, // Hydrogen Peroxide
  { cid: 962,        category: "inorganic-misc",          }, // Water
  { cid: 1176,       category: "inorganic-misc",          }, // Urea
  { cid: 5234,       category: "inorganic-misc",          }, // Sodium Chloride
  { cid: 10112,      category: "inorganic-misc",          }, // Calcium Carbonate
  { cid: 10340,      category: "inorganic-misc",          }, // Sodium Carbonate
  { cid: 24261,      category: "inorganic-misc",          }, // Silica
  { cid: 24682,      category: "inorganic-misc",          }, // Sulfur trioxide
  { cid: 516875,     category: "inorganic-misc",          }, // Potassium Permanganate

  // --- Alkanes (14) ---
  { cid: 356,        category: "alkanes",                 }, // Octane
  { cid: 6324,       category: "alkanes",                 }, // Ethane
  { cid: 6334,       category: "alkanes",                 }, // Propane
  { cid: 6351,       category: "alkanes",                 }, // Cyclopropane
  { cid: 6360,       category: "alkanes",                 }, // Isobutane
  { cid: 7843,       category: "alkanes",                 }, // Butane
  { cid: 7962,       category: "alkanes",                 }, // Methylcyclohexane
  { cid: 8003,       category: "alkanes",                 }, // Pentane
  { cid: 8058,       category: "alkanes",                 }, // Hexane
  { cid: 8078,       category: "alkanes",                 }, // Cyclohexane
  { cid: 8900,       category: "alkanes",                 }, // Heptane
  { cid: 9253,       category: "alkanes",                 }, // Cyclopentane
  { cid: 10041,      category: "alkanes",                 }, // Neopentane
  { cid: 10907,      category: "alkanes",                 }, // 2,2,4-Trimethylpentane

  // --- Alkenes, alkynes & aromatics (16) ---
  { cid: 241,        category: "unsaturated-aromatic",    }, // Benzene
  { cid: 931,        category: "unsaturated-aromatic",    }, // Naphthalene
  { cid: 995,        category: "unsaturated-aromatic",    }, // Phenanthrene
  { cid: 1140,       category: "unsaturated-aromatic",    }, // Toluene
  { cid: 6326,       category: "unsaturated-aromatic",    }, // Acetylene
  { cid: 6335,       category: "unsaturated-aromatic",    }, // Propyne
  { cid: 6557,       category: "unsaturated-aromatic",    }, // Isoprene
  { cid: 7237,       category: "unsaturated-aromatic",    }, // O-Xylene
  { cid: 7500,       category: "unsaturated-aromatic",    }, // Ethylbenzene
  { cid: 7501,       category: "unsaturated-aromatic",    }, // Styrene
  { cid: 7844,       category: "unsaturated-aromatic",    }, // 1-Butene
  { cid: 7845,       category: "unsaturated-aromatic",    }, // 1,3-Butadiene
  { cid: 8079,       category: "unsaturated-aromatic",    }, // Cyclohexene
  { cid: 8252,       category: "unsaturated-aromatic",    }, // Propylene
  { cid: 8418,       category: "unsaturated-aromatic",    }, // Anthracene
  { cid: 10419,      category: "unsaturated-aromatic",    }, // Dimethylacetylene

  // --- Alcohols, ethers & phenols (18) ---
  { cid: 174,        category: "alcohols-ethers",         }, // Ethylene Glycol
  { cid: 244,        category: "alcohols-ethers",         }, // Benzyl Alcohol
  { cid: 263,        category: "alcohols-ethers",         }, // 1-Butanol
  { cid: 289,        category: "alcohols-ethers",         }, // Catechol
  { cid: 702,        category: "alcohols-ethers",         }, // Ethanol
  { cid: 753,        category: "alcohols-ethers",         }, // Glycerol
  { cid: 785,        category: "alcohols-ethers",         }, // Hydroquinone
  { cid: 887,        category: "alcohols-ethers",         }, // Methanol
  { cid: 996,        category: "alcohols-ethers",         }, // Phenol
  { cid: 1030,       category: "alcohols-ethers",         }, // Propylene Glycol
  { cid: 1031,       category: "alcohols-ethers",         }, // 1-Propanol
  { cid: 3283,       category: "alcohols-ethers",         }, // Diethyl Ether
  { cid: 3776,       category: "alcohols-ethers",         }, // Isopropanol
  { cid: 5054,       category: "alcohols-ethers",         }, // Resorcinol
  { cid: 6386,       category: "alcohols-ethers",         }, // tert-Butanol
  { cid: 7519,       category: "alcohols-ethers",         }, // Anisole
  { cid: 8028,       category: "alcohols-ethers",         }, // Tetrahydrofuran
  { cid: 31275,      category: "alcohols-ethers",         }, // 1,4-Dioxane

  // --- Aldehydes & ketones (18) ---
  { cid: 177,        category: "aldehydes-ketones",       }, // Acetaldehyde
  { cid: 180,        category: "aldehydes-ketones",       }, // Acetone
  { cid: 240,        category: "aldehydes-ketones",       }, // Benzaldehyde
  { cid: 261,        category: "aldehydes-ketones",       }, // Butanal
  { cid: 527,        category: "aldehydes-ketones",       }, // Propanal
  { cid: 650,        category: "aldehydes-ketones",       }, // Butanedione
  { cid: 712,        category: "aldehydes-ketones",       }, // Formaldehyde
  { cid: 751,        category: "aldehydes-ketones",       }, // Glyceraldehyde
  { cid: 1183,       category: "aldehydes-ketones",       }, // Vanillin
  { cid: 2537,       category: "aldehydes-ketones",       }, // Camphor
  { cid: 3102,       category: "aldehydes-ketones",       }, // Benzophenone
  { cid: 3485,       category: "aldehydes-ketones",       }, // Glutaraldehyde
  { cid: 6569,       category: "aldehydes-ketones",       }, // Methyl Ethyl Ketone
  { cid: 7410,       category: "aldehydes-ketones",       }, // Acetophenone
  { cid: 7847,       category: "aldehydes-ketones",       }, // Acrolein
  { cid: 7967,       category: "aldehydes-ketones",       }, // Cyclohexanone
  { cid: 637511,     category: "aldehydes-ketones",       }, // Cinnamaldehyde
  { cid: 638011,     category: "aldehydes-ketones",       }, // Citral

  // --- Carboxylic acids & esters (18) ---
  { cid: 243,        category: "carboxylic-esters",       }, // Benzoic Acid
  { cid: 264,        category: "carboxylic-esters",       }, // Butyric Acid
  { cid: 284,        category: "carboxylic-esters",       }, // Formic Acid
  { cid: 311,        category: "carboxylic-esters",       }, // Citric Acid
  { cid: 338,        category: "carboxylic-esters",       }, // Salicylic Acid
  { cid: 612,        category: "carboxylic-esters",       }, // Lactic Acid
  { cid: 867,        category: "carboxylic-esters",       }, // Malonic Acid
  { cid: 971,        category: "carboxylic-esters",       }, // Oxalic Acid
  { cid: 1032,       category: "carboxylic-esters",       }, // Propionic Acid
  { cid: 1110,       category: "carboxylic-esters",       }, // Succinic Acid
  { cid: 2244,       category: "carboxylic-esters",       }, // Aspirin
  { cid: 4133,       category: "carboxylic-esters",       }, // Methyl Salicylate
  { cid: 5281,       category: "carboxylic-esters",       }, // Stearic Acid
  { cid: 6581,       category: "carboxylic-esters",       }, // Acrylic Acid
  { cid: 6584,       category: "carboxylic-esters",       }, // Methyl Acetate
  { cid: 7762,       category: "carboxylic-esters",       }, // Ethyl butyrate
  { cid: 8857,       category: "carboxylic-esters",       }, // Ethyl Acetate
  { cid: 31276,      category: "carboxylic-esters",       }, // Isoamyl Acetate

  // --- Amines, amides & N-heterocycles (16) ---
  { cid: 178,        category: "amines-nitrogen",         }, // Acetamide
  { cid: 674,        category: "amines-nitrogen",         }, // Dimethylamine
  { cid: 795,        category: "amines-nitrogen",         }, // Imidazole
  { cid: 798,        category: "amines-nitrogen",         }, // Indole
  { cid: 1044,       category: "amines-nitrogen",         }, // Purine
  { cid: 1049,       category: "amines-nitrogen",         }, // Pyridine
  { cid: 1146,       category: "amines-nitrogen",         }, // Trimethylamine
  { cid: 3301,       category: "amines-nitrogen",         }, // Ethylenediamine
  { cid: 3520,       category: "amines-nitrogen",         }, // Guanidine
  { cid: 4837,       category: "amines-nitrogen",         }, // Piperazine
  { cid: 6115,       category: "amines-nitrogen",         }, // Aniline
  { cid: 6329,       category: "amines-nitrogen",         }, // Methylamine
  { cid: 6341,       category: "amines-nitrogen",         }, // Ethylamine
  { cid: 8027,       category: "amines-nitrogen",         }, // Pyrrole
  { cid: 8082,       category: "amines-nitrogen",         }, // Piperidine
  { cid: 9260,       category: "amines-nitrogen",         }, // Pyrimidine

  // --- Amino acids (20) ---
  { cid: 750,        category: "amino-acids",             }, // Glycine
  { cid: 5862,       category: "amino-acids",             }, // L-(+)-Cysteine
  { cid: 5950,       category: "amino-acids",             }, // L-Alanine
  { cid: 5951,       category: "amino-acids",             }, // L-Serine
  { cid: 5960,       category: "amino-acids",             }, // L-Aspartic Acid
  { cid: 5961,       category: "amino-acids",             }, // L-Glutamine
  { cid: 5962,       category: "amino-acids",             }, // L-Lysine
  { cid: 6057,       category: "amino-acids",             }, // L-Tyrosine
  { cid: 6106,       category: "amino-acids",             }, // L-Leucine
  { cid: 6137,       category: "amino-acids",             }, // L-Methionine
  { cid: 6140,       category: "amino-acids",             }, // L-Phenylalanine
  { cid: 6267,       category: "amino-acids",             }, // (-)-Asparagine
  { cid: 6274,       category: "amino-acids",             }, // L-Histidine
  { cid: 6287,       category: "amino-acids",             }, // L-Valine
  { cid: 6288,       category: "amino-acids",             }, // L-Threonine
  { cid: 6305,       category: "amino-acids",             }, // L-Tryptophan
  { cid: 6306,       category: "amino-acids",             }, // L-Isoleucine
  { cid: 6322,       category: "amino-acids",             }, // L-Arginine
  { cid: 33032,      category: "amino-acids",             }, // L-Glutamic Acid
  { cid: 145742,     category: "amino-acids",             }, // L-Proline

  // --- Carbohydrates (17) ---
  { cid: 670,        category: "carbohydrates",           }, // Dihydroxyacetone
  { cid: 5780,       category: "carbohydrates",           }, // Sorbitol
  { cid: 5793,       category: "carbohydrates",           }, // D-Glucose
  { cid: 5988,       category: "carbohydrates",           }, // Sucrose
  { cid: 6036,       category: "carbohydrates",           }, // D-Galactose
  { cid: 6134,       category: "carbohydrates",           }, // beta-Lactose
  { cid: 7427,       category: "carbohydrates",           }, // Trehalose
  { cid: 17106,      category: "carbohydrates",           }, // L-Fucose
  { cid: 18950,      category: "carbohydrates",           }, // D-Mannose
  { cid: 135191,     category: "carbohydrates",           }, // D-Xylose
  { cid: 439174,     category: "carbohydrates",           }, // N-Acetyl-D-Glucosamine
  { cid: 439178,     category: "carbohydrates",           }, // Cellobiose
  { cid: 439186,     category: "carbohydrates",           }, // Maltose
  { cid: 439213,     category: "carbohydrates",           }, // D-Glucosamine
  { cid: 2723872,    category: "carbohydrates",           }, // D-Fructose
  { cid: 5460005,    category: "carbohydrates",           }, // 2-Deoxyribose, D-
  { cid: 10975657,   category: "carbohydrates",           }, // D-Ribose

  // --- Vitamins (16) ---
  { cid: 936,        category: "vitamins",                }, // Nicotinamide
  { cid: 938,        category: "vitamins",                }, // Nicotinic Acid
  { cid: 1054,       category: "vitamins",                }, // Pyridoxine
  { cid: 1130,       category: "vitamins",                }, // Thiamine
  { cid: 4055,       category: "vitamins",                }, // Menadione
  { cid: 6613,       category: "vitamins",                }, // Pantothenic Acid
  { cid: 14985,      category: "vitamins",                }, // Vitamin E
  { cid: 171548,     category: "vitamins",                }, // Biotin
  { cid: 445354,     category: "vitamins",                }, // Retinol
  { cid: 493570,     category: "vitamins",                }, // Riboflavin
  { cid: 5280793,    category: "vitamins",                }, // Ergocalciferol
  { cid: 5280795,    category: "vitamins",                }, // Vitamin D3
  { cid: 5284607,    category: "vitamins",                }, // Phylloquinone
  { cid: 54670067,   category: "vitamins",                }, // L-Ascorbic Acid
  { cid: 135398658,  category: "vitamins",                }, // Folic Acid
  { cid: 166596686,  category: "vitamins",                }, // Cyanocobalamin

  // --- Pharmaceuticals (14) ---
  { cid: 1983,       category: "pharma",                  }, // Acetaminophen
  { cid: 2153,       category: "pharma",                  }, // Theophylline
  { cid: 2519,       category: "pharma",                  }, // Caffeine
  { cid: 3016,       category: "pharma",                  }, // Diazepam
  { cid: 3100,       category: "pharma",                  }, // Diphenhydramine
  { cid: 3672,       category: "pharma",                  }, // Ibuprofen, (+-)-
  { cid: 3676,       category: "pharma",                  }, // Lidocaine
  { cid: 4091,       category: "pharma",                  }, // Metformin
  { cid: 4594,       category: "pharma",                  }, // Prilosec
  { cid: 5904,       category: "pharma",                  }, // Penicillin G
  { cid: 9294,       category: "pharma",                  }, // Ephedrine
  { cid: 89594,      category: "pharma",                  }, // Nicotine
  { cid: 156391,     category: "pharma",                  }, // Naproxen
  { cid: 5288826,    category: "pharma",                  }, // Morphine

  // --- Hormones, neurotransmitters & nucleobases (16) ---
  { cid: 119,        category: "biomolecules-neuro",      }, // Gamma-Aminobutyric Acid
  { cid: 187,        category: "biomolecules-neuro",      }, // Acetylcholine
  { cid: 190,        category: "biomolecules-neuro",      }, // Adenine
  { cid: 597,        category: "biomolecules-neuro",      }, // Cytosine
  { cid: 681,        category: "biomolecules-neuro",      }, // Dopamine
  { cid: 774,        category: "biomolecules-neuro",      }, // Histamine
  { cid: 896,        category: "biomolecules-neuro",      }, // Melatonin
  { cid: 5202,       category: "biomolecules-neuro",      }, // Serotonin
  { cid: 5754,       category: "biomolecules-neuro",      }, // Cortisol
  { cid: 5757,       category: "biomolecules-neuro",      }, // Estradiol
  { cid: 5816,       category: "biomolecules-neuro",      }, // Epinephrine
  { cid: 5994,       category: "biomolecules-neuro",      }, // Progesterone
  { cid: 5997,       category: "biomolecules-neuro",      }, // Cholesterol
  { cid: 6013,       category: "biomolecules-neuro",      }, // Testosterone
  { cid: 439260,     category: "biomolecules-neuro",      }, // Norepinephrine
  { cid: 135398634,  category: "biomolecules-neuro",      }, // Guanine

  // --- Halogenated & industrial chemicals (16) ---
  { cid: 11,         category: "halogenated-industrial",  }, // 1,2-Dichloroethane
  { cid: 679,        category: "halogenated-industrial",  }, // Dimethyl Sulfoxide
  { cid: 713,        category: "halogenated-industrial",  }, // Formamide
  { cid: 768,        category: "halogenated-industrial",  }, // Hydrogen Cyanide
  { cid: 5943,       category: "halogenated-industrial",  }, // Carbon Tetrachloride
  { cid: 6212,       category: "halogenated-industrial",  }, // Chloroform
  { cid: 6228,       category: "halogenated-industrial",  }, // Dimethylformamide
  { cid: 6338,       category: "halogenated-industrial",  }, // Vinyl Chloride
  { cid: 6342,       category: "halogenated-industrial",  }, // Acetonitrile
  { cid: 6344,       category: "halogenated-industrial",  }, // Dichloromethane
  { cid: 6354,       category: "halogenated-industrial",  }, // Ethylene Oxide
  { cid: 6375,       category: "halogenated-industrial",  }, // Nitromethane
  { cid: 6391,       category: "halogenated-industrial",  }, // Dichlorodifluoromethane
  { cid: 6575,       category: "halogenated-industrial",  }, // Trichloroethylene
  { cid: 7964,       category: "halogenated-industrial",  }, // Chlorobenzene
  { cid: 31373,      category: "halogenated-industrial",  }, // Tetrachloroethylene

];
